name: Version & Publish Packages

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

env:
  # See https://consoledonottrack.com/
  DO_NOT_TRACK: '1'

jobs:
  build-and-publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Configure NPM token
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Changesets Pull Request or Trigger an NPM Publish
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Choose Build Step
        id: build-step-decider
        run:
          echo "step-name=${{ steps.changesets.outputs.hasChangesets == 'false' && 'prepack' || 'release:next' }}" >>
          $GITHUB_OUTPUT
      - name: Choose Build Version
        id: build-version-decider
        run: echo "build-version=${{ steps.changesets.outputs.pullRequestNumber}}" >> $GITHUB_OUTPUT

      - name: 'Stop: hasChangesets'
        run: echo ${{ steps.changesets.outputs.hasChangesets }}
      - name: 'Stop: pullRequestNumber'
        run: echo ${{ steps.changesets.outputs.pullRequestNumber }}
      - name: 'Stop: step-name'
        run: echo ${{ steps.build-step-decider.outputs.step-name }}
      - name: 'Stop: build-version-decider'
        run: echo ${{ steps.build-version-decider.outputs.build-version }}

      # - name: Run Release Step
      #   run: pnpm ${{ steps.build-step-decider.outputs.step-name }}
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
